version: "3.9"

services:

  server:
    container_name: games-server
    build: .
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: "production"
      DATABASE_URL: ${DATABASE_URL}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${PGDATABASE}

  db:
    container_name: games-postgres
    image: "postgres"
    ports:
      - 5432:5432
    restart: always
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
